# We whitelist branches, as we don't really need to build dev-branches.
# Remember to add release branches, both here and to .travis.yml.
branches:
  only:
    - master

install:
  # Using '-y' and 'refreshenv' as a workaround to:
  # https://github.com/haskell/cabal/issues/3687
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y ghc --version 8.0.1 --ignore-dependencies
  - choco install -y cabal-head -pre
  - refreshenv
  # See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found#comment_42195491
  # NB: Do this after refreshenv, otherwise it will be clobbered!
  - set PATH=%APPDATA%\cabal\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\msys64\usr\bin;%PATH%
  - cabal --version
  - cabal %CABOPTS% update
  - cabal install --only-dependencies --enable-tests

environment:
  global:
    CABOPTS:  "--store-dir=C:\\SR"

cache:
  - dist-newstyle
  - "C:\\sr"

build_script:
  - cabal configure --enable-tests && cabal build && cabal test

artifacts:
  - path: dist\build\elm\elm.exe
  

deploy:
  description: 'Elm compiler fix'
  provider: GitHub
  auth_token:
    secure: 8429bc742281421da042dd69d02b76616b2275e3
  artifact: dist\build\elm\elm.exe
  draft: false
  prerelease: false
  on:
    branch: master # release from master branch only
  